"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DOWNLOAD_FILE = exports.AUTH_FILE = exports.FLOMO_PLAYWRIGHT_CACHE_LOC = exports.FLOMO_CACHE_LOC = void 0;
const path = window.require ? window.require('path') : null;
const os = window.require ? window.require('os') : null;
const homeDir = os ? os.homedir() : '';
exports.FLOMO_CACHE_LOC = path ? path.join(homeDir, "/.flomo/cache/") : "/.flomo/cache/";
exports.FLOMO_PLAYWRIGHT_CACHE_LOC = path ? path.join(homeDir, "/.flomo/cache/playwright/") : "/.flomo/cache/playwright/";
exports.AUTH_FILE = exports.FLOMO_PLAYWRIGHT_CACHE_LOC + 'flomo_auth.json';
exports.DOWNLOAD_FILE = exports.FLOMO_PLAYWRIGHT_CACHE_LOC + 'flomo_export.zip';
